server:
  port: 8081

spring:
  application:
    name: auth-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka
