server:
    port: 8083

jwt:
    secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0OTIwNDczNiwiaWF0IjoxNjQ5MjA0NzM2fQ.GwRh0jIeWx-2eRk8AHncjgowjjQcz7NLxgEe02npYlA
    expiration: 36000000

spring:
    application:
        name: producer-service

    datasource:
        url: jdbc:postgresql://localhost:5432/desafio
        username: postgres
        password: postgres

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            - hibernate.format_sql: true
            - properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect

    kafka:
        bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
        admin:
            properties:
                - bootstrap.servers: localhost:19092,localhost:29092,localhost:39092
        producer:
            client-id: producer-service-id
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:9001/eureka